# A comprehensive word list provided by user
WORD_LIST = [
    {'text': 'abandon', 'diff': 3, 'def': 'To leave something or someone behind forever.', 'type': ['verb'], 'synonym': 'desert'},
    {'text': 'abdicate', 'diff': 4, 'def': 'To give up a position of power or responsibility.', 'type': ['verb'], 'synonym': 'relinquish'},
    {'text': 'abhor', 'diff': 4, 'def': 'To hate something very much.', 'type': ['verb'], 'synonym': 'detest'},
    {'text': 'abide', 'diff': 3, 'def': 'To accept or obey a rule or decision.', 'type': ['verb'], 'synonym': 'tolerate'},
    {'text': 'abject', 'diff': 4, 'def': 'Extremely bad, unpleasant, or without hope.', 'type': ['adjective'], 'synonym': 'wretched'},
    {'text': 'abolish', 'diff': 3, 'def': 'To officially end a law or system.', 'type': ['verb'], 'synonym': 'eliminate'},
    {'text': 'abrupt', 'diff': 3, 'def': 'Sudden and unexpected.', 'type': ['adjective'], 'synonym': 'sudden'},
    {'text': 'absurd', 'diff': 3, 'def': 'Wildly unreasonable or silly.', 'type': ['adjective'], 'synonym': 'ridiculous'},
    {'text': 'abundant', 'diff': 3, 'def': 'Existing in large quantities.', 'type': ['adjective'], 'synonym': 'plentiful'},
    {'text': 'abuse', 'diff': 3, 'def': 'Cruel or violent treatment of someone; or to treat badly.', 'type': ['noun', 'verb'], 'synonym': 'mistreat'},
    {'text': 'accelerate', 'diff': 3, 'def': 'To move or happen more quickly.', 'type': ['verb'], 'synonym': 'speed'},
    {'text': 'accessible', 'diff': 3, 'def': 'Easy to reach, enter, or use.', 'type': ['adjective'], 'synonym': 'reachable'},
    {'text': 'acclaim', 'diff': 4, 'def': 'Strong praise for someone or something.', 'type': ['noun', 'verb'], 'synonym': 'applaud'},
    {'text': 'accommodate', 'diff': 4, 'def': 'To provide space or help for someone.', 'type': ['verb'], 'synonym': 'house'},
    {'text': 'accompany', 'diff': 2, 'def': 'To go somewhere with someone.', 'type': ['verb'], 'synonym': 'escort'},
    {'text': 'accomplice', 'diff': 4, 'def': 'A person who helps another do something wrong.', 'type': ['noun'], 'synonym': 'partner'},
    {'text': 'accomplish', 'diff': 3, 'def': 'To successfully achieve something.', 'type': ['verb'], 'synonym': 'achieve'},
    {'text': 'accord', 'diff': 4, 'def': 'To give or grant; also an agreement.', 'type': ['verb', 'noun'], 'synonym': 'grant'},
    {'text': 'accountable', 'diff': 3, 'def': 'Responsible for what you do and its results.', 'type': ['adjective'], 'synonym': 'answerable'},
    {'text': 'accumulate', 'diff': 4, 'def': 'To gather or build up over time.', 'type': ['verb'], 'synonym': 'collect'},
    {'text': 'accurate', 'diff': 2, 'def': 'Correct and without mistakes.', 'type': ['adjective'], 'synonym': 'precise'},
    {'text': 'accuse', 'diff': 3, 'def': 'To say that someone has done something wrong.', 'type': ['verb'], 'synonym': 'blame'},
    {'text': 'ache', 'diff': 1, 'def': 'To feel a continuous, dull pain.', 'type': ['verb', 'noun'], 'synonym': 'hurt'},
    {'text': 'acknowledge', 'diff': 3, 'def': 'To accept or admit that something is true.', 'type': ['verb'], 'synonym': 'admit'},
    {'text': 'acquaint', 'diff': 4, 'def': 'To make someone aware of or familiar with something.', 'type': ['verb'], 'synonym': 'familiarise'},
    {'text': 'acquire', 'diff': 3, 'def': 'To get or obtain something.', 'type': ['verb'], 'synonym': 'gain'},
    {'text': 'acre', 'diff': 1, 'def': 'A unit used to measure land area.', 'type': ['noun'], 'synonym': 'field'},
    {'text': 'adamant', 'diff': 4, 'def': 'Refusing to change your mind.', 'type': ['adjective'], 'synonym': 'firm'},
    {'text': 'adept', 'diff': 4, 'def': 'Very skilled at something.', 'type': ['adjective'], 'synonym': 'expert'},
    {'text': 'adequate', 'diff': 2, 'def': 'Good enough in quality or quantity.', 'type': ['adjective'], 'synonym': 'sufficient'},
    {'text': 'adjacent', 'diff': 4, 'def': 'Next to or very near something.', 'type': ['adjective'], 'synonym': 'neighbouring'},
    {'text': 'adjoin', 'diff': 4, 'def': 'To be next to and joined with something.', 'type': ['verb'], 'synonym': 'border'},
    {'text': 'adjust', 'diff': 2, 'def': 'To change something slightly to make it better.', 'type': ['verb'], 'synonym': 'modify'},
    {'text': 'admire', 'diff': 2, 'def': 'To respect and approve of someone.', 'type': ['verb'], 'synonym': 'appreciate'},
    {'text': 'admonish', 'diff': 4, 'def': 'To scold or warn someone firmly.', 'type': ['verb'], 'synonym': 'reprimand'},
    {'text': 'adorable', 'diff': 2, 'def': 'Very cute and easy to love.', 'type': ['adjective'], 'synonym': 'lovable'},
    {'text': 'adorn', 'diff': 4, 'def': 'To decorate and make more beautiful.', 'type': ['verb'], 'synonym': 'decorate'},
    {'text': 'adverse', 'diff': 4, 'def': 'Harmful or not helpful.', 'type': ['adjective'], 'synonym': 'unfavourable'},
    {'text': 'advocate', 'diff': 4, 'def': 'To publicly support an idea; also a supporter.', 'type': ['verb', 'noun'], 'synonym': 'champion'},
    {'text': 'aerial', 'diff': 3, 'def': 'Happening in the air; also a TV or radio antenna.', 'type': ['adjective', 'noun'], 'synonym': 'overhead'},
    {'text': 'affable', 'diff': 4, 'def': 'Friendly and easy to talk to.', 'type': ['adjective'], 'synonym': 'amiable'},
    {'text': 'affect', 'diff': 2, 'def': 'To influence or change something.', 'type': ['verb'], 'synonym': 'influence'},
    {'text': 'affluent', 'diff': 4, 'def': 'Having a lot of money and wealth.', 'type': ['adjective'], 'synonym': 'rich'},
    {'text': 'aggressive', 'diff': 3, 'def': 'Ready to fight or attack; very forceful.', 'type': ['adjective'], 'synonym': 'hostile'},
    {'text': 'aghast', 'diff': 4, 'def': 'Filled with shock or horror.', 'type': ['adjective'], 'synonym': 'horrified'},
    {'text': 'agile', 'diff': 3, 'def': 'Able to move quickly and easily.', 'type': ['adjective'], 'synonym': 'nimble'},
    {'text': 'agitate', 'diff': 4, 'def': 'To disturb or upset; also to campaign for change.', 'type': ['verb'], 'synonym': 'upset'},
    {'text': 'ailment', 'diff': 3, 'def': 'A minor illness or health problem.', 'type': ['noun'], 'synonym': 'illness'},
    {'text': 'allege', 'diff': 4, 'def': 'To claim that something is true without proof.', 'type': ['verb'], 'synonym': 'claim'},
    {'text': 'alliance', 'diff': 3, 'def': 'A group formed to help and support each other.', 'type': ['noun'], 'synonym': 'partnership'},
    {'text': 'allocate', 'diff': 3, 'def': 'To share out or assign resources or tasks.', 'type': ['verb'], 'synonym': 'assign'},
    {'text': 'allude', 'diff': 4, 'def': 'To mention something in an indirect way.', 'type': ['verb'], 'synonym': 'hint'},
    {'text': 'aloof', 'diff': 4, 'def': 'Distant and not friendly or involved.', 'type': ['adjective'], 'synonym': 'detached'},
    {'text': 'alter', 'diff': 2, 'def': 'To change something slightly.', 'type': ['verb'], 'synonym': 'change'},
    {'text': 'altruistic', 'diff': 5, 'def': 'Showing selfless concern for others.', 'type': ['adjective'], 'synonym': 'unselfish'},
    {'text': 'amaze', 'diff': 1, 'def': 'To surprise someone greatly.', 'type': ['verb'], 'synonym': 'astonish'},
    {'text': 'ambiguous', 'diff': 4, 'def': 'Having more than one possible meaning.', 'type': ['adjective'], 'synonym': 'unclear'},
    {'text': 'ambitious', 'diff': 2, 'def': 'Having a strong desire to succeed.', 'type': ['adjective'], 'synonym': 'driven'},
    {'text': 'amiable', 'diff': 4, 'def': 'Pleasant and friendly.', 'type': ['adjective'], 'synonym': 'friendly'},
    {'text': 'amuse', 'diff': 2, 'def': 'To make someone laugh or smile.', 'type': ['verb'], 'synonym': 'entertain'},
    {'text': 'ancient', 'diff': 2, 'def': 'Very old, from a long time ago.', 'type': ['adjective'], 'synonym': 'antique'},
    {'text': 'anguish', 'diff': 4, 'def': 'Severe mental or physical pain.', 'type': ['noun'], 'synonym': 'torment'},
    {'text': 'animated', 'diff': 3, 'def': 'Full of life, energy, or excitement.', 'type': ['adjective'], 'synonym': 'lively'},
    {'text': 'annex', 'diff': 4, 'def': 'To take control of land; also an added building.', 'type': ['verb', 'noun'], 'synonym': 'seize'},
    {'text': 'annual', 'diff': 1, 'def': 'Happening once every year.', 'type': ['adjective'], 'synonym': 'yearly'},
    {'text': 'antagonise', 'diff': 4, 'def': 'To make someone feel hostile or angry.', 'type': ['verb'], 'synonym': 'provoke'},
    {'text': 'anticipate', 'diff': 3, 'def': 'To expect something to happen.', 'type': ['verb'], 'synonym': 'expect'},
    {'text': 'anxious', 'diff': 2, 'def': 'Worried or nervous about something.', 'type': ['adjective'], 'synonym': 'worried'},
    {'text': 'apathy', 'diff': 4, 'def': 'A lack of interest or enthusiasm.', 'type': ['noun'], 'synonym': 'indifference'},
    {'text': 'applaud', 'diff': 2, 'def': 'To clap to show approval.', 'type': ['verb'], 'synonym': 'praise'},
    {'text': 'appraise', 'diff': 4, 'def': 'To judge the value or quality of something.', 'type': ['verb'], 'synonym': 'evaluate'},
    {'text': 'apprehensive', 'diff': 4, 'def': 'Worried that something bad may happen.', 'type': ['adjective'], 'synonym': 'uneasy'},
    {'text': 'apt', 'diff': 3, 'def': 'Suitable; or likely to do something.', 'type': ['adjective'], 'synonym': 'appropriate'},
    {'text': 'arbitrary', 'diff': 4, 'def': 'Based on random choice rather than reason.', 'type': ['adjective'], 'synonym': 'random'},
    {'text': 'ardent', 'diff': 4, 'def': 'Very enthusiastic or passionate.', 'type': ['adjective'], 'synonym': 'fervent'},
    {'text': 'arduous', 'diff': 4, 'def': 'Very difficult and tiring.', 'type': ['adjective'], 'synonym': 'strenuous'},
    {'text': 'arid', 'diff': 3, 'def': 'Extremely dry, with very little rain.', 'type': ['adjective'], 'synonym': 'dry'},
    {'text': 'arrogant', 'diff': 3, 'def': 'Behaving as if you are better than others.', 'type': ['adjective'], 'synonym': 'proud'},
    {'text': 'articulate', 'diff': 4, 'def': 'Able to express ideas clearly in words.', 'type': ['adjective', 'verb'], 'synonym': 'eloquent'},
    {'text': 'ascend', 'diff': 3, 'def': 'To move or climb upwards.', 'type': ['verb'], 'synonym': 'rise'},
    {'text': 'ascertain', 'diff': 4, 'def': 'To find out something for certain.', 'type': ['verb'], 'synonym': 'discover'},
    {'text': 'ashamed', 'diff': 2, 'def': 'Feeling guilty or embarrassed about something.', 'type': ['adjective'], 'synonym': 'guilty'},
    {'text': 'aspire', 'diff': 3, 'def': 'To have a strong desire to achieve something.', 'type': ['verb'], 'synonym': 'strive'},
    {'text': 'assent', 'diff': 4, 'def': 'Official agreement or approval.', 'type': ['noun', 'verb'], 'synonym': 'consent'},
    {'text': 'assert', 'diff': 3, 'def': 'To state something firmly and confidently.', 'type': ['verb'], 'synonym': 'declare'},
    {'text': 'assess', 'diff': 3, 'def': 'To judge or estimate the value or level of something.', 'type': ['verb'], 'synonym': 'evaluate'},
    {'text': 'asset', 'diff': 2, 'def': 'A useful or valuable thing or person.', 'type': ['noun'], 'synonym': 'advantage'},
    {'text': 'astonish', 'diff': 3, 'def': 'To surprise someone greatly.', 'type': ['verb'], 'synonym': 'amaze'},
    {'text': 'astute', 'diff': 4, 'def': 'Able to understand situations and use this to your advantage.', 'type': ['adjective'], 'synonym': 'shrewd'},
    {'text': 'atrocious', 'diff': 4, 'def': 'Extremely bad or cruel.', 'type': ['adjective'], 'synonym': 'terrible'},
    {'text': 'attain', 'diff': 3, 'def': 'To succeed in reaching or achieving something.', 'type': ['verb'], 'synonym': 'achieve'},
    {'text': 'attentive', 'diff': 3, 'def': 'Paying close attention to something or someone.', 'type': ['adjective'], 'synonym': 'alert'},
    {'text': 'attribute', 'diff': 4, 'def': 'A quality of someone; or to credit something to a cause.', 'type': ['noun', 'verb'], 'synonym': 'trait'},
    {'text': 'audacious', 'diff': 5, 'def': 'Very bold, sometimes shockingly so.', 'type': ['adjective'], 'synonym': 'daring'},
    {'text': 'augment', 'diff': 4, 'def': 'To increase the size or value of something.', 'type': ['verb'], 'synonym': 'increase'},
    {'text': 'austere', 'diff': 5, 'def': 'Plain and without comfort; or very strict.', 'type': ['adjective'], 'synonym': 'severe'},
    {'text': 'authentic', 'diff': 3, 'def': 'Genuine and real, not fake.', 'type': ['adjective'], 'synonym': 'genuine'},
    {'text': 'avarice', 'diff': 5, 'def': 'Extreme greed for money or wealth.', 'type': ['noun'], 'synonym': 'greed'},
    {'text': 'averse', 'diff': 4, 'def': 'Strongly disliking or opposed to something.', 'type': ['adjective'], 'synonym': 'opposed'},
    {'text': 'avid', 'diff': 3, 'def': 'Very eager or enthusiastic.', 'type': ['adjective'], 'synonym': 'keen'},
    {'text': 'baffle', 'diff': 3, 'def': 'To completely confuse someone.', 'type': ['verb'], 'synonym': 'puzzle'},
    {'text': 'barren', 'diff': 3, 'def': 'Unable to produce plants or offspring.', 'type': ['adjective'], 'synonym': 'sterile'},
    {'text': 'bashful', 'diff': 2, 'def': 'Shy and easily embarrassed.', 'type': ['adjective'], 'synonym': 'shy'},
    {'text': 'belligerent', 'diff': 5, 'def': 'Hostile and eager to fight.', 'type': ['adjective'], 'synonym': 'aggressive'},
    {'text': 'benevolent', 'diff': 4, 'def': 'Kind and wanting to do good.', 'type': ['adjective'], 'synonym': 'kind'},
    {'text': 'benign', 'diff': 4, 'def': 'Gentle and harmless.', 'type': ['adjective'], 'synonym': 'harmless'},
    {'text': 'bequest', 'diff': 4, 'def': 'Money or property left to someone in a will.', 'type': ['noun'], 'synonym': 'legacy'},
    {'text': 'bewilder', 'diff': 3, 'def': 'To confuse someone completely.', 'type': ['verb'], 'synonym': 'perplex'},
    {'text': 'bias', 'diff': 3, 'def': 'Unfair preference for or against something.', 'type': ['noun'], 'synonym': 'prejudice'},
    {'text': 'bizarre', 'diff': 3, 'def': 'Very strange and unusual.', 'type': ['adjective'], 'synonym': 'odd'},
    {'text': 'bleak', 'diff': 3, 'def': 'Cold, empty, and without hope.', 'type': ['adjective'], 'synonym': 'grim'},
    {'text': 'boast', 'diff': 2, 'def': 'To proudly talk about your achievements.', 'type': ['verb'], 'synonym': 'brag'},
    {'text': 'bolster', 'diff': 4, 'def': 'To support or strengthen.', 'type': ['verb'], 'synonym': 'reinforce'},
    {'text': 'bond', 'diff': 2, 'def': 'A close connection between people or things.', 'type': ['noun'], 'synonym': 'tie'},
    {'text': 'brisk', 'diff': 3, 'def': 'Quick and energetic.', 'type': ['adjective'], 'synonym': 'lively'},
    {'text': 'brutal', 'diff': 3, 'def': 'Extremely cruel or harsh.', 'type': ['adjective'], 'synonym': 'cruel'},
    {'text': 'burden', 'diff': 3, 'def': 'A heavy duty or responsibility.', 'type': ['noun'], 'synonym': 'load'},
    {'text': 'candid', 'diff': 4, 'def': 'Honest and saying what you really think.', 'type': ['adjective'], 'synonym': 'frank'},
    {'text': 'capable', 'diff': 2, 'def': 'Having the ability to do something well.', 'type': ['adjective'], 'synonym': 'able'},
    {'text': 'capricious', 'diff': 5, 'def': 'Changing mood or behaviour suddenly.', 'type': ['adjective'], 'synonym': 'unpredictable'},
    {'text': 'captive', 'diff': 3, 'def': 'Kept as a prisoner or unable to escape.', 'type': ['adjective', 'noun'], 'synonym': 'prisoner'},
    {'text': 'caution', 'diff': 2, 'def': 'Care taken to avoid danger or mistakes.', 'type': ['noun'], 'synonym': 'care'},
    {'text': 'cease', 'diff': 3, 'def': 'To stop doing something.', 'type': ['verb'], 'synonym': 'stop'},
    {'text': 'censure', 'diff': 5, 'def': 'Strong criticism or disapproval.', 'type': ['noun', 'verb'], 'synonym': 'condemnation'},
    {'text': 'chaotic', 'diff': 3, 'def': 'Very confused and disorganised.', 'type': ['adjective'], 'synonym': 'disorderly'},
    {'text': 'charitable', 'diff': 3, 'def': 'Helpful to the poor; kind in judging others.', 'type': ['adjective'], 'synonym': 'generous'},
    {'text': 'cherish', 'diff': 3, 'def': 'To love and care for something deeply.', 'type': ['verb'], 'synonym': 'treasure'},
    {'text': 'chronicle', 'diff': 4, 'def': 'A record of events in order; or to record them.', 'type': ['noun', 'verb'], 'synonym': 'record'},
    {'text': 'citadel', 'diff': 4, 'def': 'A strong fortress protecting a city.', 'type': ['noun'], 'synonym': 'fortress'},
    {'text': 'civic', 'diff': 3, 'def': 'Related to a town or the people who live there.', 'type': ['adjective'], 'synonym': 'municipal'},
    {'text': 'clarify', 'diff': 2, 'def': 'To make something easier to understand.', 'type': ['verb'], 'synonym': 'explain'},
    {'text': 'clash', 'diff': 2, 'def': 'To fight or argue; or to not go well together.', 'type': ['verb', 'noun'], 'synonym': 'conflict'},
    {'text': 'coarse', 'diff': 3, 'def': 'Rough in texture; or rude in manner.', 'type': ['adjective'], 'synonym': 'rough'},
    {'text': 'coax', 'diff': 3, 'def': 'To gently persuade someone to do something.', 'type': ['verb'], 'synonym': 'persuade'},
    {'text': 'coerce', 'diff': 4, 'def': 'To force someone to do something.', 'type': ['verb'], 'synonym': 'compel'},
    {'text': 'coherent', 'diff': 4, 'def': 'Logical and easy to understand.', 'type': ['adjective'], 'synonym': 'logical'},
    {'text': 'coincide', 'diff': 4, 'def': 'To happen at the same time or match.', 'type': ['verb'], 'synonym': 'overlap'},
    {'text': 'collaborate', 'diff': 3, 'def': 'To work together with others.', 'type': ['verb'], 'synonym': 'cooperate'},
    {'text': 'collapse', 'diff': 2, 'def': 'To fall down suddenly.', 'type': ['verb'], 'synonym': 'crumple'},
    {'text': 'colossal', 'diff': 3, 'def': 'Extremely large.', 'type': ['adjective'], 'synonym': 'huge'},
    {'text': 'commend', 'diff': 3, 'def': 'To praise or approve of someone.', 'type': ['verb'], 'synonym': 'praise'},
    {'text': 'commodity', 'diff': 4, 'def': 'A product that can be bought or sold.', 'type': ['noun'], 'synonym': 'goods'},
    {'text': 'compassion', 'diff': 3, 'def': 'Deep sympathy and desire to help others.', 'type': ['noun'], 'synonym': 'kindness'},
    {'text': 'compatible', 'diff': 3, 'def': 'Able to exist or work together without problems.', 'type': ['adjective'], 'synonym': 'well-matched'},
    {'text': 'compel', 'diff': 3, 'def': 'To force someone to do something.', 'type': ['verb'], 'synonym': 'force'},
    {'text': 'competent', 'diff': 3, 'def': 'Having enough skill or knowledge.', 'type': ['adjective'], 'synonym': 'capable'},
    {'text': 'compile', 'diff': 3, 'def': 'To gather information into a list or book.', 'type': ['verb'], 'synonym': 'collect'},
    {'text': 'complacent', 'diff': 4, 'def': 'Too satisfied, not seeing possible danger.', 'type': ['adjective'], 'synonym': 'self-satisfied'},
    {'text': 'comprehend', 'diff': 2, 'def': 'To understand something fully.', 'type': ['verb'], 'synonym': 'understand'},
    {'text': 'comprehensive', 'diff': 3, 'def': 'Including all or nearly all details.', 'type': ['adjective'], 'synonym': 'thorough'},
    {'text': 'concise', 'diff': 3, 'def': 'Giving a lot of information in few words.', 'type': ['adjective'], 'synonym': 'brief'},
    {'text': 'concur', 'diff': 4, 'def': 'To agree with someone or something.', 'type': ['verb'], 'synonym': 'agree'},
    {'text': 'condemn', 'diff': 3, 'def': 'To express strong disapproval of something.', 'type': ['verb'], 'synonym': 'denounce'},
    {'text': 'condense', 'diff': 3, 'def': 'To make something shorter or more concentrated.', 'type': ['verb'], 'synonym': 'compress'},
    {'text': 'confer', 'diff': 4, 'def': 'To discuss or to give an honour or title.', 'type': ['verb'], 'synonym': 'consult'},
    {'text': 'confide', 'diff': 3, 'def': 'To share a secret with someone you trust.', 'type': ['verb'], 'synonym': 'reveal'},
    {'text': 'confine', 'diff': 3, 'def': 'To keep someone or something within limits.', 'type': ['verb'], 'synonym': 'restrict'},
    {'text': 'conform', 'diff': 3, 'def': 'To behave in the same way as others or rules.', 'type': ['verb'], 'synonym': 'follow'},
    {'text': 'confront', 'diff': 3, 'def': 'To face up to and deal with a problem or person.', 'type': ['verb'], 'synonym': 'face'},
    {'text': 'congested', 'diff': 3, 'def': 'Crowded and blocked with traffic or people.', 'type': ['adjective'], 'synonym': 'crowded'},
    {'text': 'conjecture', 'diff': 5, 'def': 'An opinion based on guesswork rather than proof.', 'type': ['noun', 'verb'], 'synonym': 'guess'},
    {'text': 'conscience', 'diff': 3, 'def': 'The sense of right and wrong in a person.', 'type': ['noun'], 'synonym': 'morals'},
    {'text': 'conscientious', 'diff': 5, 'def': 'Careful and wanting to do work well.', 'type': ['adjective'], 'synonym': 'thorough'},
    {'text': 'consecutive', 'diff': 3, 'def': 'Following one after another without a break.', 'type': ['adjective'], 'synonym': 'successive'},
    {'text': 'consent', 'diff': 2, 'def': 'Permission for something to happen.', 'type': ['noun', 'verb'], 'synonym': 'agreement'},
    {'text': 'conserve', 'diff': 3, 'def': 'To protect something from harm or waste.', 'type': ['verb'], 'synonym': 'preserve'},
    {'text': 'considerate', 'diff': 2, 'def': 'Thoughtful and careful not to upset others.', 'type': ['adjective'], 'synonym': 'thoughtful'},
    {'text': 'conspicuous', 'diff': 4, 'def': 'Very easy to see or notice.', 'type': ['adjective'], 'synonym': 'obvious'},
    {'text': 'constraint', 'diff': 4, 'def': 'A limit or restriction on what you can do.', 'type': ['noun'], 'synonym': 'restriction'},
    {'text': 'contaminate', 'diff': 4, 'def': 'To make something dirty or unsafe.', 'type': ['verb'], 'synonym': 'pollute'},
    {'text': 'contemplate', 'diff': 4, 'def': 'To think deeply about something.', 'type': ['verb'], 'synonym': 'ponder'},
    {'text': 'contend', 'diff': 4, 'def': 'To compete or argue that something is true.', 'type': ['verb'], 'synonym': 'argue'},
    {'text': 'contour', 'diff': 4, 'def': 'The shape or outline of something.', 'type': ['noun'], 'synonym': 'outline'},
    {'text': 'contradict', 'diff': 3, 'def': 'To say the opposite of what someone has said.', 'type': ['verb'], 'synonym': 'oppose'},
    {'text': 'contrast', 'diff': 2, 'def': 'A difference between two things.', 'type': ['noun', 'verb'], 'synonym': 'difference'},
    {'text': 'contribute', 'diff': 2, 'def': 'To give or add something to help.', 'type': ['verb'], 'synonym': 'donate'},
    {'text': 'controversial', 'diff': 4, 'def': 'Causing disagreement or argument.', 'type': ['adjective'], 'synonym': 'disputed'},
    {'text': 'convene', 'diff': 4, 'def': 'To come together for a meeting.', 'type': ['verb'], 'synonym': 'assemble'},
    {'text': 'conventional', 'diff': 3, 'def': 'Usual, traditional, or accepted by most people.', 'type': ['adjective'], 'synonym': 'traditional'},
    {'text': 'convey', 'diff': 3, 'def': 'To communicate or carry from one place to another.', 'type': ['verb'], 'synonym': 'communicate'},
    {'text': 'convict', 'diff': 3, 'def': 'To decide in court that someone is guilty; or that person.', 'type': ['verb', 'noun'], 'synonym': 'find guilty'},
    {'text': 'copious', 'diff': 4, 'def': 'Large in amount or number.', 'type': ['adjective'], 'synonym': 'abundant'},
    {'text': 'cordial', 'diff': 4, 'def': 'Warm and friendly.', 'type': ['adjective'], 'synonym': 'friendly'},
    {'text': 'corpulent', 'diff': 5, 'def': 'Fat and overweight.', 'type': ['adjective'], 'synonym': 'obese'},
    {'text': 'corrupt', 'diff': 3, 'def': 'Dishonest, especially for money or power.', 'type': ['adjective', 'verb'], 'synonym': 'dishonest'},
    {'text': 'curse', 'diff': 3, 'def': 'A wish for something bad to happen; or a swear word.', 'type': ['noun', 'verb'], 'synonym': 'hex'},
    {'text': 'curtail', 'diff': 4, 'def': 'To reduce or limit something.', 'type': ['verb'], 'synonym': 'shorten'},
    {'text': 'dainty', 'diff': 3, 'def': 'Delicate, small, and pretty.', 'type': ['adjective'], 'synonym': 'delicate'},
    {'text': 'daring', 'diff': 2, 'def': 'Brave and willing to take risks.', 'type': ['adjective'], 'synonym': 'bold'},
    {'text': 'daunt', 'diff': 4, 'def': 'To make someone feel nervous or less confident.', 'type': ['verb'], 'synonym': 'discourage'},
    {'text': 'debate', 'diff': 2, 'def': 'A formal discussion on an issue.', 'type': ['noun', 'verb'], 'synonym': 'discussion'},
    {'text': 'debris', 'diff': 3, 'def': 'Scattered pieces left after something is destroyed.', 'type': ['noun'], 'synonym': 'rubble'},
    {'text': 'decay', 'diff': 2, 'def': 'To rot or break down over time.', 'type': ['verb', 'noun'], 'synonym': 'rot'},
    {'text': 'deceit', 'diff': 3, 'def': 'The act of lying or tricking someone.', 'type': ['noun'], 'synonym': 'dishonesty'},
    {'text': 'deceive', 'diff': 3, 'def': 'To make someone believe something that is not true.', 'type': ['verb'], 'synonym': 'mislead'},
    {'text': 'decisive', 'diff': 3, 'def': 'Able to make decisions quickly and firmly.', 'type': ['adjective'], 'synonym': 'determined'},
    {'text': 'decline', 'diff': 2, 'def': 'To become weaker; or to politely refuse.', 'type': ['verb', 'noun'], 'synonym': 'refuse'},
    {'text': 'decompose', 'diff': 3, 'def': 'To break down into smaller parts, often by rotting.', 'type': ['verb'], 'synonym': 'decay'},
    {'text': 'defect', 'diff': 3, 'def': 'A fault or imperfection.', 'type': ['noun'], 'synonym': 'flaw'},
    {'text': 'defiant', 'diff': 3, 'def': 'Refusing to obey authority.', 'type': ['adjective'], 'synonym': 'rebellious'},
    {'text': 'deficiency', 'diff': 4, 'def': 'A lack of something that is needed.', 'type': ['noun'], 'synonym': 'shortage'},
    {'text': 'definitive', 'diff': 4, 'def': 'Final and cannot be changed or improved.', 'type': ['adjective'], 'synonym': 'final'},
    {'text': 'degrade', 'diff': 3, 'def': 'To treat someone without respect or to worsen something.', 'type': ['verb'], 'synonym': 'demean'},
    {'text': 'dejected', 'diff': 3, 'def': 'Very sad and disappointed.', 'type': ['adjective'], 'synonym': 'downcast'},
    {'text': 'deliberate', 'diff': 3, 'def': 'Done on purpose; or to think carefully.', 'type': ['adjective', 'verb'], 'synonym': 'intentional'},
    {'text': 'delineate', 'diff': 5, 'def': 'To describe or mark the exact details of something.', 'type': ['verb'], 'synonym': 'describe'},
    {'text': 'delinquent', 'diff': 4, 'def': 'Failing to do what law or duty requires.', 'type': ['adjective', 'noun'], 'synonym': 'offending'},
    {'text': 'delirious', 'diff': 4, 'def': 'In an excited or confused state, often from illness.', 'type': ['adjective'], 'synonym': 'wild'},
    {'text': 'deluge', 'diff': 4, 'def': 'A severe flood or a large amount of something.', 'type': ['noun', 'verb'], 'synonym': 'flood'},
    {'text': 'demeanour', 'diff': 4, 'def': 'The way a person behaves or appears.', 'type': ['noun'], 'synonym': 'manner'},
    {'text': 'demolish', 'diff': 3, 'def': 'To destroy a building completely.', 'type': ['verb'], 'synonym': 'knock down'},
    {'text': 'denounce', 'diff': 4, 'def': 'To publicly criticise or accuse.', 'type': ['verb'], 'synonym': 'condemn'},
    {'text': 'dense', 'diff': 2, 'def': 'Tightly packed; or slow to understand.', 'type': ['adjective'], 'synonym': 'thick'},
    {'text': 'deplete', 'diff': 4, 'def': 'To use up most of something.', 'type': ['verb'], 'synonym': 'exhaust'},
    {'text': 'deplore', 'diff': 4, 'def': 'To strongly disapprove of something.', 'type': ['verb'], 'synonym': 'condemn'},
    {'text': 'deprive', 'diff': 3, 'def': 'To take something important away from someone.', 'type': ['verb'], 'synonym': 'rob'},
    {'text': 'derelict', 'diff': 4, 'def': 'Abandoned and in bad condition.', 'type': ['adjective'], 'synonym': 'run-down'},
    {'text': 'deride', 'diff': 5, 'def': 'To laugh at or mock something.', 'type': ['verb'], 'synonym': 'ridicule'},
    {'text': 'descend', 'diff': 2, 'def': 'To move downwards.', 'type': ['verb'], 'synonym': 'fall'},
    {'text': 'desolate', 'diff': 4, 'def': 'Empty, lonely, and sad.', 'type': ['adjective'], 'synonym': 'bleak'},
    {'text': 'despair', 'diff': 3, 'def': 'A complete loss of hope.', 'type': ['noun', 'verb'], 'synonym': 'hopelessness'},
    {'text': 'despise', 'diff': 3, 'def': 'To strongly dislike and have no respect for someone.', 'type': ['verb'], 'synonym': 'hate'},
    {'text': 'destitute', 'diff': 4, 'def': 'Extremely poor and lacking basic needs.', 'type': ['adjective'], 'synonym': 'impoverished'},
    {'text': 'deter', 'diff': 3, 'def': 'To discourage someone from doing something.', 'type': ['verb'], 'synonym': 'discourage'},
    {'text': 'detrimental', 'diff': 4, 'def': 'Causing harm or damage.', 'type': ['adjective'], 'synonym': 'harmful'},
    {'text': 'devastate', 'diff': 3, 'def': 'To destroy or deeply upset.', 'type': ['verb'], 'synonym': 'ruin'},
    {'text': 'devise', 'diff': 3, 'def': 'To invent or plan something.', 'type': ['verb'], 'synonym': 'design'},
    {'text': 'devote', 'diff': 2, 'def': 'To give time or effort to something you care about.', 'type': ['verb'], 'synonym': 'dedicate'},
    {'text': 'dexterous', 'diff': 5, 'def': 'Skilful with your hands or mind.', 'type': ['adjective'], 'synonym': 'skilled'},
    {'text': 'dignified', 'diff': 3, 'def': 'Calm, serious, and worthy of respect.', 'type': ['adjective'], 'synonym': 'respectable'},
    {'text': 'dilapidated', 'diff': 5, 'def': 'In very bad condition from age or lack of care.', 'type': ['adjective'], 'synonym': 'run-down'},
    {'text': 'diligent', 'diff': 3, 'def': 'Working hard and carefully.', 'type': ['adjective'], 'synonym': 'hard-working'},
    {'text': 'diminish', 'diff': 3, 'def': 'To make or become smaller or weaker.', 'type': ['verb'], 'synonym': 'reduce'},
    {'text': 'dire', 'diff': 4, 'def': 'Very serious or urgent.', 'type': ['adjective'], 'synonym': 'terrible'},
    {'text': 'discreet', 'diff': 4, 'def': 'Careful not to attract attention or reveal secrets.', 'type': ['adjective'], 'synonym': 'tactful'},
    {'text': 'disdain', 'diff': 4, 'def': 'A strong feeling of dislike and lack of respect.', 'type': ['noun', 'verb'], 'synonym': 'contempt'},
    {'text': 'dismal', 'diff': 3, 'def': 'Very sad or without hope; gloomy.', 'type': ['adjective'], 'synonym': 'gloomy'},
    {'text': 'dismantle', 'diff': 3, 'def': 'To take something apart.', 'type': ['verb'], 'synonym': 'disassemble'},
    {'text': 'disperse', 'diff': 3, 'def': 'To scatter in different directions.', 'type': ['verb'], 'synonym': 'scatter'},
    {'text': 'dispute', 'diff': 3, 'def': 'A serious disagreement or argument.', 'type': ['noun', 'verb'], 'synonym': 'argument'},
    {'text': 'disrupt', 'diff': 3, 'def': 'To interrupt and cause confusion.', 'type': ['verb'], 'synonym': 'disturb'},
    {'text': 'distinct', 'diff': 3, 'def': 'Clearly separate and different.', 'type': ['adjective'], 'synonym': 'clear'},
    {'text': 'distort', 'diff': 3, 'def': 'To change the shape or meaning so it is unclear.', 'type': ['verb'], 'synonym': 'twist'},
    {'text': 'distraught', 'diff': 4, 'def': 'Very upset and worried.', 'type': ['adjective'], 'synonym': 'distressed'},
    {'text': 'divert', 'diff': 3, 'def': 'To change the direction of something; or to entertain.', 'type': ['verb'], 'synonym': 'redirect'},
    {'text': 'docile', 'diff': 4, 'def': 'Quiet and easy to control.', 'type': ['adjective'], 'synonym': 'obedient'},
    {'text': 'dominate', 'diff': 2, 'def': 'To have control or power over something.', 'type': ['verb'], 'synonym': 'control'},
    {'text': 'donate', 'diff': 2, 'def': 'To give money or goods to help others.', 'type': ['verb'], 'synonym': 'contribute'},
    {'text': 'dormant', 'diff': 4, 'def': 'Not active now but able to become active later.', 'type': ['adjective'], 'synonym': 'inactive'},
    {'text': 'drastic', 'diff': 3, 'def': 'Extreme and sudden.', 'type': ['adjective'], 'synonym': 'extreme'},
    {'text': 'dubious', 'diff': 4, 'def': 'Not sure or not to be trusted.', 'type': ['adjective'], 'synonym': 'doubtful'},
    {'text': 'durable', 'diff': 3, 'def': 'Able to last a long time without damage.', 'type': ['adjective'], 'synonym': 'hard-wearing'},
    {'text': 'earnest', 'diff': 3, 'def': 'Serious and sincere.', 'type': ['adjective'], 'synonym': 'serious'},
    {'text': 'ecstatic', 'diff': 3, 'def': 'Extremely happy.', 'type': ['adjective'], 'synonym': 'overjoyed'},
    {'text': 'elaborate', 'diff': 3, 'def': 'Having many details; to explain in more detail.', 'type': ['adjective', 'verb'], 'synonym': 'detailed'},
    {'text': 'elated', 'diff': 3, 'def': 'Very happy and excited.', 'type': ['adjective'], 'synonym': 'thrilled'},
    {'text': 'elegant', 'diff': 2, 'def': 'Stylish and graceful.', 'type': ['adjective'], 'synonym': 'graceful'},
    {'text': 'eliminate', 'diff': 2, 'def': 'To remove or get rid of something.', 'type': ['verb'], 'synonym': 'remove'},
    {'text': 'eloquent', 'diff': 4, 'def': 'Able to express ideas clearly and well.', 'type': ['adjective'], 'synonym': 'articulate'},
    {'text': 'elude', 'diff': 4, 'def': 'To avoid being caught; or to escape understanding.', 'type': ['verb'], 'synonym': 'evade'},
    {'text': 'emerge', 'diff': 2, 'def': 'To come out from somewhere.', 'type': ['verb'], 'synonym': 'appear'},
    {'text': 'empathy', 'diff': 3, 'def': "The ability to understand another's feelings.", 'type': ['noun'], 'synonym': 'understanding'},
    {'text': 'empower', 'diff': 3, 'def': 'To give someone power or confidence.', 'type': ['verb'], 'synonym': 'enable'},
    {'text': 'endeavour', 'diff': 3, 'def': 'A serious attempt to do something difficult.', 'type': ['noun', 'verb'], 'synonym': 'effort'},
    {'text': 'endure', 'diff': 3, 'def': 'To suffer something difficult and keep going.', 'type': ['verb'], 'synonym': 'bear'},
    {'text': 'enforce', 'diff': 2, 'def': 'To make people obey a law or rule.', 'type': ['verb'], 'synonym': 'impose'},
    {'text': 'engulf', 'diff': 3, 'def': 'To surround and cover completely.', 'type': ['verb'], 'synonym': 'swallow'},
    {'text': 'enhance', 'diff': 3, 'def': 'To improve the quality or value of something.', 'type': ['verb'], 'synonym': 'improve'},
    {'text': 'enigmatic', 'diff': 4, 'def': 'Mysterious and difficult to understand.', 'type': ['adjective'], 'synonym': 'mysterious'},
    {'text': 'enormous', 'diff': 2, 'def': 'Very large in size.', 'type': ['adjective'], 'synonym': 'huge'},
    {'text': 'enthusiastic', 'diff': 2, 'def': 'Showing strong enjoyment and interest.', 'type': ['adjective'], 'synonym': 'eager'},
    {'text': 'entice', 'diff': 3, 'def': 'To attract or tempt someone with something pleasant.', 'type': ['verb'], 'synonym': 'tempt'},
    {'text': 'equitable', 'diff': 4, 'def': 'Fair and reasonable.', 'type': ['adjective'], 'synonym': 'fair'},
    {'text': 'eradicate', 'diff': 4, 'def': 'To completely get rid of something.', 'type': ['verb'], 'synonym': 'destroy'},
    {'text': 'erratic', 'diff': 4, 'def': 'Not regular or predictable.', 'type': ['adjective'], 'synonym': 'unpredictable'},
    {'text': 'escalate', 'diff': 3, 'def': 'To increase or intensify quickly.', 'type': ['verb'], 'synonym': 'intensify'},
    {'text': 'essential', 'diff': 2, 'def': 'Very important and necessary.', 'type': ['adjective'], 'synonym': 'vital'},
    {'text': 'esteem', 'diff': 3, 'def': 'Respect and admiration for someone.', 'type': ['noun', 'verb'], 'synonym': 'respect'},
    {'text': 'evade', 'diff': 3, 'def': 'To avoid or escape from something.', 'type': ['verb'], 'synonym': 'avoid'},
    {'text': 'evident', 'diff': 2, 'def': 'Clear and easy to see or understand.', 'type': ['adjective'], 'synonym': 'obvious'},
    {'text': 'exaggerate', 'diff': 2, 'def': 'To make something sound bigger or better than it is.', 'type': ['verb'], 'synonym': 'overstate'},
    {'text': 'exasperate', 'diff': 4, 'def': 'To make someone very annoyed.', 'type': ['verb'], 'synonym': 'irritate'},
    {'text': 'excel', 'diff': 2, 'def': 'To be very good at something.', 'type': ['verb'], 'synonym': 'outshine'},
    {'text': 'exclude', 'diff': 2, 'def': 'To leave someone or something out.', 'type': ['verb'], 'synonym': 'omit'},
    {'text': 'exert', 'diff': 3, 'def': 'To use effort or power to do something.', 'type': ['verb'], 'synonym': 'apply'},
    {'text': 'exhaustive', 'diff': 4, 'def': 'Including everything; very thorough.', 'type': ['adjective'], 'synonym': 'thorough'},
    {'text': 'expel', 'diff': 3, 'def': 'To force someone to leave a place.', 'type': ['verb'], 'synonym': 'eject'},
    {'text': 'explicit', 'diff': 3, 'def': 'Clear and exact, with no doubt.', 'type': ['adjective'], 'synonym': 'clear'},
    {'text': 'exploit', 'diff': 3, 'def': 'To use something unfairly for your own benefit.', 'type': ['verb'], 'synonym': 'take advantage'},
    {'text': 'extinct', 'diff': 2, 'def': 'No longer existing.', 'type': ['adjective'], 'synonym': 'gone'},
    {'text': 'fabulous', 'diff': 2, 'def': 'Extremely good or wonderful.', 'type': ['adjective'], 'synonym': 'marvellous'},
    {'text': 'facilitate', 'diff': 4, 'def': 'To make something easier to do.', 'type': ['verb'], 'synonym': 'ease'},
    {'text': 'falter', 'diff': 3, 'def': 'To hesitate or lose strength.', 'type': ['verb'], 'synonym': 'waver'},
    {'text': 'feeble', 'diff': 3, 'def': 'Very weak.', 'type': ['adjective'], 'synonym': 'weak'},
    {'text': 'feign', 'diff': 4, 'def': 'To pretend to have a feeling or be ill.', 'type': ['verb'], 'synonym': 'pretend'},
    {'text': 'fervent', 'diff': 4, 'def': 'Showing strong feelings or enthusiasm.', 'type': ['adjective'], 'synonym': 'passionate'},
    {'text': 'fickle', 'diff': 4, 'def': 'Changing interests or feelings often.', 'type': ['adjective'], 'synonym': 'changeable'},
    {'text': 'flamboyant', 'diff': 4, 'def': 'Very colourful or noticeable in behaviour or style.', 'type': ['adjective'], 'synonym': 'showy'},
    {'text': 'flaw', 'diff': 2, 'def': 'A small fault or mistake.', 'type': ['noun'], 'synonym': 'defect'},
    {'text': 'flourish', 'diff': 3, 'def': 'To grow or develop successfully.', 'type': ['verb'], 'synonym': 'thrive'},
    {'text': 'forbid', 'diff': 2, 'def': 'To order someone not to do something.', 'type': ['verb'], 'synonym': 'prohibit'},
    {'text': 'foresee', 'diff': 3, 'def': 'To know or expect something before it happens.', 'type': ['verb'], 'synonym': 'predict'},
    {'text': 'formidable', 'diff': 4, 'def': 'Very powerful or impressive and difficult to defeat.', 'type': ['adjective'], 'synonym': 'intimidating'},
    {'text': 'fortify', 'diff': 3, 'def': 'To strengthen a place or feeling.', 'type': ['verb'], 'synonym': 'strengthen'},
    {'text': 'fragrant', 'diff': 2, 'def': 'Having a pleasant smell.', 'type': ['adjective'], 'synonym': 'scented'},
    {'text': 'frantic', 'diff': 3, 'def': 'Wild with fear or anxiety.', 'type': ['adjective'], 'synonym': 'panicked'},
    {'text': 'fraud', 'diff': 4, 'def': 'The crime of cheating someone for money or advantage.', 'type': ['noun'], 'synonym': 'deception'},
    {'text': 'frigid', 'diff': 4, 'def': 'Extremely cold.', 'type': ['adjective'], 'synonym': 'icy'},
    {'text': 'frustrate', 'diff': 2, 'def': 'To make someone feel annoyed by preventing progress.', 'type': ['verb'], 'synonym': 'annoy'},
    {'text': 'gallant', 'diff': 4, 'def': 'Brave and noble; or polite to women.', 'type': ['adjective'], 'synonym': 'brave'},
    {'text': 'garment', 'diff': 2, 'def': 'A piece of clothing.', 'type': ['noun'], 'synonym': 'clothing'},
    {'text': 'gaunt', 'diff': 4, 'def': 'Very thin, often because of illness or hunger.', 'type': ['adjective'], 'synonym': 'bony'},
    {'text': 'generate', 'diff': 2, 'def': 'To produce or create something.', 'type': ['verb'], 'synonym': 'produce'},
    {'text': 'genuine', 'diff': 2, 'def': 'Real and sincere.', 'type': ['adjective'], 'synonym': 'authentic'},
    {'text': 'glib', 'diff': 4, 'def': 'Speaking easily but without sincerity.', 'type': ['adjective'], 'synonym': 'slick'},
    {'text': 'gloomy', 'diff': 2, 'def': 'Dark or making you feel sad.', 'type': ['adjective'], 'synonym': 'dreary'},
    {'text': 'glutton', 'diff': 4, 'def': 'Someone who eats or wants too much.', 'type': ['noun'], 'synonym': 'overeater'},
    {'text': 'gracious', 'diff': 3, 'def': 'Polite, kind, and pleasant.', 'type': ['adjective'], 'synonym': 'courteous'},
    {'text': 'gratitude', 'diff': 2, 'def': 'The feeling of being thankful.', 'type': ['noun'], 'synonym': 'thankfulness'},
    {'text': 'grievous', 'diff': 4, 'def': 'Very serious or causing great pain.', 'type': ['adjective'], 'synonym': 'severe'},
    {'text': 'grim', 'diff': 3, 'def': 'Very serious or unpleasant.', 'type': ['adjective'], 'synonym': 'gloomy'},
    {'text': 'grotesque', 'diff': 4, 'def': 'Strangely ugly or disturbing.', 'type': ['adjective'], 'synonym': 'distorted'},
    {'text': 'harass', 'diff': 3, 'def': 'To trouble or annoy someone repeatedly.', 'type': ['verb'], 'synonym': 'pester'},
    {'text': 'hardship', 'diff': 2, 'def': 'Severe suffering or difficulty.', 'type': ['noun'], 'synonym': 'difficulty'},
    {'text': 'harsh', 'diff': 2, 'def': 'Rough, unpleasant, or cruel.', 'type': ['adjective'], 'synonym': 'severe'},
    {'text': 'haughty', 'diff': 4, 'def': 'Proud and looking down on others.', 'type': ['adjective'], 'synonym': 'arrogant'},
    {'text': 'hazard', 'diff': 2, 'def': 'Something that can cause danger.', 'type': ['noun'], 'synonym': 'danger'},
    {'text': 'heed', 'diff': 3, 'def': 'To pay careful attention to something.', 'type': ['verb', 'noun'], 'synonym': 'notice'},
    {'text': 'helpless', 'diff': 1, 'def': 'Unable to do anything to help yourself.', 'type': ['adjective'], 'synonym': 'powerless'},
    {'text': 'hostile', 'diff': 3, 'def': 'Very unfriendly or aggressive.', 'type': ['adjective'], 'synonym': 'antagonistic'},
    {'text': 'humble', 'diff': 2, 'def': 'Not proud; or simple and modest.', 'type': ['adjective'], 'synonym': 'modest'},
    {'text': 'hypocrite', 'diff': 4, 'def': 'Someone who says one thing but does another.', 'type': ['noun'], 'synonym': 'pretender'},
    {'text': 'identical', 'diff': 2, 'def': 'Exactly the same in every detail.', 'type': ['adjective'], 'synonym': 'the same'},
    {'text': 'idle', 'diff': 2, 'def': 'Not active or working; lazy.', 'type': ['adjective'], 'synonym': 'lazy'},
    {'text': 'ignite', 'diff': 3, 'def': 'To set on fire or start a strong feeling.', 'type': ['verb'], 'synonym': 'spark'},
    {'text': 'illuminate', 'diff': 3, 'def': 'To light up or make something clear.', 'type': ['verb'], 'synonym': 'light'},
    {'text': 'illustrious', 'diff': 4, 'def': 'Very famous and admired.', 'type': ['adjective'], 'synonym': 'distinguished'},
    {'text': 'immense', 'diff': 3, 'def': 'Extremely large or great.', 'type': ['adjective'], 'synonym': 'huge'},
    {'text': 'imminent', 'diff': 4, 'def': 'About to happen very soon.', 'type': ['adjective'], 'synonym': 'impending'},
    {'text': 'impartial', 'diff': 3, 'def': 'Treating all sides fairly.', 'type': ['adjective'], 'synonym': 'fair'},
    {'text': 'imperative', 'diff': 4, 'def': 'Very important and urgent.', 'type': ['adjective'], 'synonym': 'crucial'},
    {'text': 'implement', 'diff': 3, 'def': 'To put a plan or decision into action.', 'type': ['verb'], 'synonym': 'carry out'},
    {'text': 'impoverished', 'diff': 4, 'def': 'Very poor; having little money or resources.', 'type': ['adjective'], 'synonym': 'poor'},
    {'text': 'imprudent', 'diff': 4, 'def': 'Not wise or careful; risky.', 'type': ['adjective'], 'synonym': 'reckless'},
    {'text': 'inadequate', 'diff': 3, 'def': 'Not good enough or too low in quality.', 'type': ['adjective'], 'synonym': 'insufficient'},
    {'text': 'incapable', 'diff': 2, 'def': 'Not able to do something.', 'type': ['adjective'], 'synonym': 'unable'},
    {'text': 'incentive', 'diff': 3, 'def': 'Something that encourages you to do something.', 'type': ['noun'], 'synonym': 'motivation'},
    {'text': 'incite', 'diff': 4, 'def': 'To encourage someone to behave violently or wrongly.', 'type': ['verb'], 'synonym': 'provoke'},
    {'text': 'incline', 'diff': 3, 'def': 'To lean; or to be likely to feel or do something.', 'type': ['verb', 'noun'], 'synonym': 'tend'},
    {'text': 'incompetent', 'diff': 3, 'def': 'Not having the skills to do something properly.', 'type': ['adjective'], 'synonym': 'inept'},
    {'text': 'incriminate', 'diff': 4, 'def': 'To make someone appear guilty of a crime.', 'type': ['verb'], 'synonym': 'implicate'},
    {'text': 'indignant', 'diff': 3, 'def': 'Angry because something seems unfair.', 'type': ['adjective'], 'synonym': 'outraged'},
    {'text': 'indispensable', 'diff': 4, 'def': 'Absolutely necessary.', 'type': ['adjective'], 'synonym': 'essential'},
    {'text': 'indolent', 'diff': 5, 'def': 'Very lazy and not wanting to work.', 'type': ['adjective'], 'synonym': 'lazy'},
    {'text': 'indulge', 'diff': 3, 'def': 'To allow yourself to enjoy something too much.', 'type': ['verb'], 'synonym': 'pamper'},
    {'text': 'inevitable', 'diff': 3, 'def': 'Certain to happen and unavoidable.', 'type': ['adjective'], 'synonym': 'unavoidable'},
    {'text': 'infer', 'diff': 3, 'def': 'To decide something from evidence, not direct statements.', 'type': ['verb'], 'synonym': 'deduce'},
    {'text': 'ingenious', 'diff': 4, 'def': 'Very clever and original.', 'type': ['adjective'], 'synonym': 'clever'},
    {'text': 'inhabit', 'diff': 2, 'def': 'To live in a place.', 'type': ['verb'], 'synonym': 'live'},
    {'text': 'inhibit', 'diff': 4, 'def': 'To hold back or prevent something.', 'type': ['verb'], 'synonym': 'restrain'},
    {'text': 'innate', 'diff': 4, 'def': 'Existing from birth rather than learned.', 'type': ['adjective'], 'synonym': 'inborn'},
    {'text': 'innovative', 'diff': 3, 'def': 'New, original, and creative.', 'type': ['adjective'], 'synonym': 'inventive'},
    {'text': 'insatiable', 'diff': 5, 'def': 'Impossible to satisfy.', 'type': ['adjective'], 'synonym': 'greedy'},
    {'text': 'insinuate', 'diff': 5, 'def': 'To suggest something bad in an indirect way.', 'type': ['verb'], 'synonym': 'imply'},
    {'text': 'insolent', 'diff': 4, 'def': 'Very rude and disrespectful.', 'type': ['adjective'], 'synonym': 'impudent'},
    {'text': 'inspect', 'diff': 2, 'def': 'To look at something carefully.', 'type': ['verb'], 'synonym': 'examine'},
    {'text': 'inspire', 'diff': 2, 'def': 'To fill someone with the urge to do something good.', 'type': ['verb'], 'synonym': 'motivate'},
    {'text': 'integrity', 'diff': 3, 'def': 'Honesty and strong moral principles.', 'type': ['noun'], 'synonym': 'honesty'},
    {'text': 'intense', 'diff': 2, 'def': 'Very strong or extreme.', 'type': ['adjective'], 'synonym': 'strong'},
    {'text': 'intervene', 'diff': 3, 'def': 'To get involved to change what is happening.', 'type': ['verb'], 'synonym': 'step in'},
    {'text': 'intimidate', 'diff': 3, 'def': 'To frighten someone into doing something.', 'type': ['verb'], 'synonym': 'bully'},
    {'text': 'intricate', 'diff': 4, 'def': 'Very detailed and complicated.', 'type': ['adjective'], 'synonym': 'complex'},
    {'text': 'introspective', 'diff': 5, 'def': 'Thinking deeply about your own feelings and thoughts.', 'type': ['adjective'], 'synonym': 'self-reflective'},
    {'text': 'intuition', 'diff': 4, 'def': 'Understanding something immediately without reasoning.', 'type': ['noun'], 'synonym': 'instinct'},
    {'text': 'invade', 'diff': 2, 'def': 'To enter a place with force.', 'type': ['verb'], 'synonym': 'attack'},
    {'text': 'invaluable', 'diff': 3, 'def': 'Extremely useful.', 'type': ['adjective'], 'synonym': 'priceless'},
    {'text': 'invariably', 'diff': 4, 'def': 'Always, without changing.', 'type': ['adverb'], 'synonym': 'always'},
    {'text': 'irate', 'diff': 3, 'def': 'Extremely angry.', 'type': ['adjective'], 'synonym': 'furious'},
    {'text': 'irksome', 'diff': 4, 'def': 'Annoying and irritating.', 'type': ['adjective'], 'synonym': 'annoying'},
    {'text': 'isolated', 'diff': 2, 'def': 'Far away from others; alone.', 'type': ['adjective'], 'synonym': 'remote'},
    {'text': 'jeopardise', 'diff': 4, 'def': 'To put something in danger of being lost or harmed.', 'type': ['verb'], 'synonym': 'endanger'},
    {'text': 'jovial', 'diff': 3, 'def': 'Cheerful and friendly.', 'type': ['adjective'], 'synonym': 'jolly'},
    {'text': 'judicious', 'diff': 4, 'def': 'Showing good judgement and sense.', 'type': ['adjective'], 'synonym': 'sensible'},
    {'text': 'keen', 'diff': 1, 'def': 'Very eager or interested.', 'type': ['adjective'], 'synonym': 'eager'},
    {'text': 'kin', 'diff': 2, 'def': 'Family members or relatives.', 'type': ['noun'], 'synonym': 'relatives'},
    {'text': 'kinetic', 'diff': 4, 'def': 'Related to movement.', 'type': ['adjective'], 'synonym': 'moving'},
    {'text': 'lament', 'diff': 4, 'def': 'To express sadness or regret.', 'type': ['verb', 'noun'], 'synonym': 'mourn'},
    {'text': 'languid', 'diff': 5, 'def': 'Moving slowly and without energy.', 'type': ['adjective'], 'synonym': 'sluggish'},
    {'text': 'lavish', 'diff': 3, 'def': 'Rich, expensive, or generous.', 'type': ['adjective', 'verb'], 'synonym': 'luxurious'},
    {'text': 'legible', 'diff': 2, 'def': 'Clear enough to read easily.', 'type': ['adjective'], 'synonym': 'readable'},
    {'text': 'lenient', 'diff': 3, 'def': 'Not strict; tolerant and forgiving.', 'type': ['adjective'], 'synonym': 'soft'},
    {'text': 'lethargic', 'diff': 4, 'def': 'Feeling very tired and lacking energy.', 'type': ['adjective'], 'synonym': 'sluggish'},
    {'text': 'liable', 'diff': 3, 'def': 'Likely to do something; legally responsible.', 'type': ['adjective'], 'synonym': 'likely'},
    {'text': 'liberate', 'diff': 3, 'def': 'To set someone free.', 'type': ['verb'], 'synonym': 'free'},
    {'text': 'limp', 'diff': 2, 'def': 'To walk with difficulty; or lacking strength.', 'type': ['verb', 'adjective'], 'synonym': 'hobble'},
    {'text': 'linear', 'diff': 3, 'def': 'In a straight line; involving one thing after another.', 'type': ['adjective'], 'synonym': 'straight'},
    {'text': 'livid', 'diff': 4, 'def': 'Extremely angry.', 'type': ['adjective'], 'synonym': 'furious'},
    {'text': 'loathe', 'diff': 4, 'def': 'To hate something very much.', 'type': ['verb'], 'synonym': 'detest'},
    {'text': 'lonesome', 'diff': 2, 'def': 'Feeling sad because you are alone.', 'type': ['adjective'], 'synonym': 'lonely'},
    {'text': 'lucrative', 'diff': 4, 'def': 'Producing a lot of money.', 'type': ['adjective'], 'synonym': 'profitable'},
    {'text': 'luminous', 'diff': 3, 'def': 'Giving off light; bright.', 'type': ['adjective'], 'synonym': 'glowing'},
    {'text': 'luxurious', 'diff': 3, 'def': 'Very comfortable and expensive.', 'type': ['adjective'], 'synonym': 'opulent'},
    {'text': 'magnify', 'diff': 2, 'def': 'To make something look larger or more important.', 'type': ['verb'], 'synonym': 'enlarge'},
    {'text': 'majestic', 'diff': 3, 'def': 'Impressive and grand.', 'type': ['adjective'], 'synonym': 'grand'},
    {'text': 'malice', 'diff': 3, 'def': 'The desire to harm others.', 'type': ['noun'], 'synonym': 'spite'},
    {'text': 'malignant', 'diff': 4, 'def': 'Very harmful or likely to cause death.', 'type': ['adjective'], 'synonym': 'deadly'},
    {'text': 'mandatory', 'diff': 3, 'def': 'Required by law or rules.', 'type': ['adjective'], 'synonym': 'compulsory'},
    {'text': 'manifest', 'diff': 4, 'def': 'Clear to see; or to show clearly.', 'type': ['adjective', 'verb'], 'synonym': 'obvious'},
    {'text': 'manipulate', 'diff': 3, 'def': 'To control or influence cleverly and sometimes unfairly.', 'type': ['verb'], 'synonym': 'control'},
    {'text': 'marvellous', 'diff': 2, 'def': 'Extremely good or impressive.', 'type': ['adjective'], 'synonym': 'wonderful'},
    {'text': 'meagre', 'diff': 3, 'def': 'Very small in amount or quality.', 'type': ['adjective'], 'synonym': 'scanty'},
    {'text': 'mediate', 'diff': 3, 'def': 'To help solve a disagreement between people.', 'type': ['verb'], 'synonym': 'arbitrate'},
    {'text': 'melancholy', 'diff': 4, 'def': 'A feeling of deep sadness.', 'type': ['noun', 'adjective'], 'synonym': 'sadness'},
    {'text': 'meticulous', 'diff': 4, 'def': 'Very careful about small details.', 'type': ['adjective'], 'synonym': 'precise'},
    {'text': 'mimic', 'diff': 2, 'def': 'To copy the way someone speaks or behaves.', 'type': ['verb', 'noun'], 'synonym': 'imitate'},
    {'text': 'miserly', 'diff': 4, 'def': 'Not willing to spend money; mean.', 'type': ['adjective'], 'synonym': 'stingy'},
    {'text': 'moderate', 'diff': 2, 'def': 'Not extreme; average.', 'type': ['adjective'], 'synonym': 'reasonable'},
    {'text': 'momentous', 'diff': 4, 'def': 'Very important and serious.', 'type': ['adjective'], 'synonym': 'significant'},
    {'text': 'morbid', 'diff': 4, 'def': 'Interested in unpleasant subjects like death.', 'type': ['adjective'], 'synonym': 'gloomy'},
    {'text': 'mundane', 'diff': 3, 'def': 'Ordinary and not exciting.', 'type': ['adjective'], 'synonym': 'dull'},
    {'text': 'murmur', 'diff': 2, 'def': 'To speak softly; a quiet continuous sound.', 'type': ['verb', 'noun'], 'synonym': 'whisper'},
    {'text': 'negligent', 'diff': 4, 'def': 'Not taking enough care.', 'type': ['adjective'], 'synonym': 'careless'},
    {'text': 'nimble', 'diff': 3, 'def': 'Quick and light in movement.', 'type': ['adjective'], 'synonym': 'agile'},
    {'text': 'notorious', 'diff': 3, 'def': 'Famous for something bad.', 'type': ['adjective'], 'synonym': 'infamous'},
    {'text': 'novice', 'diff': 3, 'def': 'A person who is new to an activity.', 'type': ['noun'], 'synonym': 'beginner'},
    {'text': 'nurture', 'diff': 3, 'def': 'To care for and help grow.', 'type': ['verb', 'noun'], 'synonym': 'care'},
    {'text': 'obdurate', 'diff': 5, 'def': 'Very stubborn and refusing to change.', 'type': ['adjective'], 'synonym': 'stubborn'},
    {'text': 'obedient', 'diff': 2, 'def': 'Doing what you are told.', 'type': ['adjective'], 'synonym': 'dutiful'},
    {'text': 'oblivious', 'diff': 3, 'def': 'Not aware of what is happening around you.', 'type': ['adjective'], 'synonym': 'unaware'},
    {'text': 'obscure', 'diff': 4, 'def': 'Not well known; or difficult to understand.', 'type': ['adjective', 'verb'], 'synonym': 'unclear'},
    {'text': 'obstinate', 'diff': 4, 'def': 'Very unwilling to change your opinion.', 'type': ['adjective'], 'synonym': 'stubborn'},
    {'text': 'obvious', 'diff': 1, 'def': 'Easy to see or understand.', 'type': ['adjective'], 'synonym': 'clear'},
    {'text': 'omen', 'diff': 3, 'def': 'A sign that something good or bad will happen.', 'type': ['noun'], 'synonym': 'sign'},
    {'text': 'ominous', 'diff': 4, 'def': 'Giving the feeling that something bad will happen.', 'type': ['adjective'], 'synonym': 'threatening'},
    {'text': 'operate', 'diff': 1, 'def': 'To work or control a machine; or do surgery.', 'type': ['verb'], 'synonym': 'run'},
    {'text': 'oppress', 'diff': 4, 'def': 'To treat people cruelly and unfairly.', 'type': ['verb'], 'synonym': 'persecute'},
    {'text': 'optimistic', 'diff': 2, 'def': 'Expecting good things to happen.', 'type': ['adjective'], 'synonym': 'hopeful'},
    {'text': 'ornate', 'diff': 4, 'def': 'Highly decorated and detailed.', 'type': ['adjective'], 'synonym': 'elaborate'},
    {'text': 'ostentatious', 'diff': 5, 'def': 'Showing off wealth or importance to impress others.', 'type': ['adjective'], 'synonym': 'showy'},
    {'text': 'overt', 'diff': 4, 'def': 'Done openly and plainly.', 'type': ['adjective'], 'synonym': 'open'},
    {'text': 'pacify', 'diff': 3, 'def': 'To calm someone who is angry or upset.', 'type': ['verb'], 'synonym': 'soothe'},
    {'text': 'palatable', 'diff': 3, 'def': 'Tasty; or acceptable to the mind.', 'type': ['adjective'], 'synonym': 'tasty'},
    {'text': 'paltry', 'diff': 4, 'def': 'Too small to be worth much.', 'type': ['adjective'], 'synonym': 'insignificant'},
    {'text': 'parched', 'diff': 3, 'def': 'Very dry or thirsty.', 'type': ['adjective'], 'synonym': 'dry'},
    {'text': 'partial', 'diff': 3, 'def': 'Not complete; or showing favour to one side.', 'type': ['adjective'], 'synonym': 'biased'},
    {'text': 'passive', 'diff': 3, 'def': 'Allowing things to happen without reacting.', 'type': ['adjective'], 'synonym': 'inactive'},
    {'text': 'paucity', 'diff': 5, 'def': 'A very small amount of something.', 'type': ['noun'], 'synonym': 'scarcity'},
    {'text': 'perceive', 'diff': 3, 'def': 'To notice or understand something.', 'type': ['verb'], 'synonym': 'notice'},
    {'text': 'peril', 'diff': 3, 'def': 'Great danger.', 'type': ['noun'], 'synonym': 'danger'},
    {'text': 'permanent', 'diff': 2, 'def': 'Lasting forever or for a long time.', 'type': ['adjective'], 'synonym': 'lasting'},
    {'text': 'perplex', 'diff': 4, 'def': 'To confuse someone very much.', 'type': ['verb'], 'synonym': 'baffle'},
    {'text': 'persecute', 'diff': 4, 'def': 'To treat someone cruelly because of their beliefs or race.', 'type': ['verb'], 'synonym': 'oppress'},
    {'text': 'persistent', 'diff': 3, 'def': 'Continuing strongly, even through difficulty.', 'type': ['adjective'], 'synonym': 'determined'},
    {'text': 'persuade', 'diff': 2, 'def': 'To convince someone to do or believe something.', 'type': ['verb'], 'synonym': 'convince'},
    {'text': 'pessimistic', 'diff': 3, 'def': 'Expecting bad things to happen.', 'type': ['adjective'], 'synonym': 'gloomy'},
    {'text': 'petty', 'diff': 3, 'def': 'Small and unimportant; mean about little things.', 'type': ['adjective'], 'synonym': 'trivial'},
    {'text': 'placid', 'diff': 4, 'def': 'Calm and peaceful.', 'type': ['adjective'], 'synonym': 'calm'},
    {'text': 'plausible', 'diff': 3, 'def': 'Seeming likely to be true.', 'type': ['adjective'], 'synonym': 'believable'},
    {'text': 'plentiful', 'diff': 2, 'def': 'Existing in large amounts.', 'type': ['adjective'], 'synonym': 'abundant'},
    {'text': 'plight', 'diff': 3, 'def': 'A difficult or sad situation.', 'type': ['noun'], 'synonym': 'difficulty'},
    {'text': 'ponder', 'diff': 3, 'def': 'To think carefully about something.', 'type': ['verb'], 'synonym': 'consider'},
    {'text': 'precaution', 'diff': 2, 'def': 'Something done to prevent harm or trouble.', 'type': ['noun'], 'synonym': 'safeguard'},
    {'text': 'precise', 'diff': 3, 'def': 'Exact and accurate.', 'type': ['adjective'], 'synonym': 'exact'},
    {'text': 'predator', 'diff': 2, 'def': 'An animal that hunts other animals.', 'type': ['noun'], 'synonym': 'hunter'},
    {'text': 'preferable', 'diff': 2, 'def': 'More desirable or better.', 'type': ['adjective'], 'synonym': 'better'},
    {'text': 'prejudice', 'diff': 3, 'def': 'Unfair dislike of someone without good reason.', 'type': ['noun', 'verb'], 'synonym': 'bias'},
    {'text': 'preliminary', 'diff': 3, 'def': 'Coming before the main event.', 'type': ['adjective', 'noun'], 'synonym': 'initial'},
    {'text': 'premature', 'diff': 3, 'def': 'Happening too early.', 'type': ['adjective'], 'synonym': 'early'},
    {'text': 'presume', 'diff': 3, 'def': 'To suppose something is true without proof.', 'type': ['verb'], 'synonym': 'assume'},
    {'text': 'prevail', 'diff': 4, 'def': 'To win or be stronger; to be common.', 'type': ['verb'], 'synonym': 'triumph'},
    {'text': 'profound', 'diff': 4, 'def': 'Very deep or serious.', 'type': ['adjective'], 'synonym': 'deep'},
    {'text': 'prohibit', 'diff': 2, 'def': 'To officially stop something from being done.', 'type': ['verb'], 'synonym': 'ban'},
    {'text': 'prominent', 'diff': 3, 'def': 'Important or easily seen.', 'type': ['adjective'], 'synonym': 'notable'},
    {'text': 'prudent', 'diff': 3, 'def': 'Sensible and careful about the future.', 'type': ['adjective'], 'synonym': 'wise'},
    {'text': 'pseudonym', 'diff': 4, 'def': 'A false name used by someone.', 'type': ['noun'], 'synonym': 'pen-name'},
    {'text': 'punctual', 'diff': 2, 'def': 'Arriving on time.', 'type': ['adjective'], 'synonym': 'on-time'},
    {'text': 'quaint', 'diff': 3, 'def': 'Attractively old-fashioned.', 'type': ['adjective'], 'synonym': 'old-fashioned'},
    {'text': 'quell', 'diff': 4, 'def': 'To stop something, especially by force.', 'type': ['verb'], 'synonym': 'suppress'},
    {'text': 'query', 'diff': 2, 'def': 'A question about something.', 'type': ['noun', 'verb'], 'synonym': 'question'},
    {'text': 'quibble', 'diff': 4, 'def': 'To argue about small, unimportant things.', 'type': ['verb', 'noun'], 'synonym': 'nitpick'},
    {'text': 'radiant', 'diff': 2, 'def': 'Shining brightly or showing great happiness.', 'type': ['adjective'], 'synonym': 'bright'},
    {'text': 'ramble', 'diff': 3, 'def': 'To walk with no clear direction; or talk in a disorganised way.', 'type': ['verb'], 'synonym': 'wander'},
    {'text': 'rancid', 'diff': 4, 'def': 'Having a bad smell due to being old or rotten.', 'type': ['adjective'], 'synonym': 'rotten'},
    {'text': 'random', 'diff': 1, 'def': 'Done without a plan or pattern.', 'type': ['adjective'], 'synonym': 'chance'},
    {'text': 'rash', 'diff': 3, 'def': 'Acting too quickly without thinking; or a skin problem.', 'type': ['adjective', 'noun'], 'synonym': 'reckless'},
    {'text': 'ravage', 'diff': 4, 'def': 'To cause great damage to something.', 'type': ['verb'], 'synonym': 'devastate'},
    {'text': 'recalcitrant', 'diff': 5, 'def': 'Refusing to obey rules or orders.', 'type': ['adjective'], 'synonym': 'stubborn'},
    {'text': 'recede', 'diff': 3, 'def': 'To move back or become weaker.', 'type': ['verb'], 'synonym': 'retreat'},
    {'text': 'reckless', 'diff': 3, 'def': 'Not caring about dangers or risks.', 'type': ['adjective'], 'synonym': 'careless'},
    {'text': 'reclusive', 'diff': 4, 'def': 'Preferring to live alone and avoid others.', 'type': ['adjective'], 'synonym': 'isolated'},
    {'text': 'refined', 'diff': 3, 'def': 'Polite and well-educated; or pure.', 'type': ['adjective'], 'synonym': 'elegant'},
    {'text': 'refute', 'diff': 4, 'def': 'To prove that something is wrong.', 'type': ['verb'], 'synonym': 'disprove'},
    {'text': 'refrain', 'diff': 3, 'def': 'To stop yourself from doing something.', 'type': ['verb'], 'synonym': 'hold back'},
    {'text': 'regret', 'diff': 1, 'def': 'To feel sorry about something you did or did not do.', 'type': ['verb', 'noun'], 'synonym': 'remorse'},
    {'text': 'reliable', 'diff': 2, 'def': 'Able to be trusted or depended on.', 'type': ['adjective'], 'synonym': 'dependable'},
    {'text': 'reluctant', 'diff': 2, 'def': 'Not wanting to do something.', 'type': ['adjective'], 'synonym': 'unwilling'},
    {'text': 'remorse', 'diff': 3, 'def': 'Deep regret for doing something wrong.', 'type': ['noun'], 'synonym': 'guilt'},
    {'text': 'renowned', 'diff': 3, 'def': 'Famous and admired for something.', 'type': ['adjective'], 'synonym': 'famous'},
    {'text': 'repel', 'diff': 3, 'def': 'To drive something away; or to disgust.', 'type': ['verb'], 'synonym': 'drive away'},
    {'text': 'replenish', 'diff': 3, 'def': 'To fill something again.', 'type': ['verb'], 'synonym': 'refill'},
    {'text': 'repress', 'diff': 4, 'def': 'To hold back feelings or actions.', 'type': ['verb'], 'synonym': 'suppress'},
    {'text': 'reproach', 'diff': 4, 'def': 'To scold or blame someone.', 'type': ['verb', 'noun'], 'synonym': 'blame'},
    {'text': 'resemble', 'diff': 2, 'def': 'To look or be like someone or something.', 'type': ['verb'], 'synonym': 'look like'},
    {'text': 'resilient', 'diff': 3, 'def': 'Able to recover quickly from problems.', 'type': ['adjective'], 'synonym': 'tough'},
    {'text': 'resolve', 'diff': 2, 'def': 'To decide firmly; or to solve a problem.', 'type': ['verb', 'noun'], 'synonym': 'settle'},
    {'text': 'resonant', 'diff': 4, 'def': 'Deep and echoing in sound; or having a lasting effect.', 'type': ['adjective'], 'synonym': 'echoing'},
    {'text': 'restrain', 'diff': 3, 'def': 'To hold back from action.', 'type': ['verb'], 'synonym': 'restrict'},
    {'text': 'retaliate', 'diff': 3, 'def': 'To hurt someone because they hurt you.', 'type': ['verb'], 'synonym': 'take revenge'},
    {'text': 'retract', 'diff': 4, 'def': 'To pull back or withdraw a statement.', 'type': ['verb'], 'synonym': 'withdraw'},
    {'text': 'reveal', 'diff': 1, 'def': 'To make something known that was hidden.', 'type': ['verb'], 'synonym': 'show'},
    {'text': 'reverence', 'diff': 4, 'def': 'Great respect and admiration.', 'type': ['noun'], 'synonym': 'respect'},
    {'text': 'rigid', 'diff': 2, 'def': 'Stiff and not bending; not flexible in ideas.', 'type': ['adjective'], 'synonym': 'stiff'},
    {'text': 'robust', 'diff': 3, 'def': 'Strong and healthy.', 'type': ['adjective'], 'synonym': 'strong'},
    {'text': 'rudimentary', 'diff': 4, 'def': 'Basic and not developed.', 'type': ['adjective'], 'synonym': 'basic'},
    {'text': 'ruthless', 'diff': 3, 'def': 'Cruel and without pity.', 'type': ['adjective'], 'synonym': 'merciless'},
    {'text': 'savour', 'diff': 3, 'def': 'To enjoy the taste or experience of something fully.', 'type': ['verb', 'noun'], 'synonym': 'enjoy'},
    {'text': 'scarce', 'diff': 2, 'def': 'Hard to find; not enough.', 'type': ['adjective'], 'synonym': 'rare'},
    {'text': 'scorn', 'diff': 3, 'def': 'A strong feeling that something is worthless.', 'type': ['noun', 'verb'], 'synonym': 'contempt'},
    {'text': 'scrutinise', 'diff': 4, 'def': 'To examine something very carefully.', 'type': ['verb'], 'synonym': 'inspect'},
    {'text': 'secluded', 'diff': 3, 'def': 'Quiet and far away from other people.', 'type': ['adjective'], 'synonym': 'isolated'},
    {'text': 'serene', 'diff': 3, 'def': 'Calm and peaceful.', 'type': ['adjective'], 'synonym': 'calm'},
    {'text': 'shrewd', 'diff': 3, 'def': 'Clever and good at judging situations.', 'type': ['adjective'], 'synonym': 'astute'},
    {'text': 'simultaneous', 'diff': 4, 'def': 'Happening at the same time.', 'type': ['adjective'], 'synonym': 'concurrent'},
    {'text': 'skeptical', 'diff': 3, 'def': 'Doubting that something is true or useful.', 'type': ['adjective'], 'synonym': 'doubtful'},
    {'text': 'sluggish', 'diff': 2, 'def': 'Moving or working more slowly than normal.', 'type': ['adjective'], 'synonym': 'slow'},
    {'text': 'sly', 'diff': 2, 'def': 'Clever at hiding what you are doing.', 'type': ['adjective'], 'synonym': 'cunning'},
    {'text': 'solitary', 'diff': 3, 'def': 'Done alone or existing alone.', 'type': ['adjective'], 'synonym': 'alone'},
    {'text': 'somber', 'diff': 3, 'def': 'Dark in colour; or very serious and sad.', 'type': ['adjective'], 'synonym': 'gloomy'},
    {'text': 'soothe', 'diff': 2, 'def': 'To make someone or something calmer or less painful.', 'type': ['verb'], 'synonym': 'comfort'},
    {'text': 'sovereign', 'diff': 4, 'def': 'The supreme ruler of a country.', 'type': ['noun', 'adjective'], 'synonym': 'ruler'},
    {'text': 'spontaneous', 'diff': 3, 'def': 'Done suddenly without planning.', 'type': ['adjective'], 'synonym': 'impulsive'},
    {'text': 'squalid', 'diff': 4, 'def': 'Very dirty and unpleasant.', 'type': ['adjective'], 'synonym': 'filthy'},
    {'text': 'stagnant', 'diff': 4, 'def': 'Not moving or changing; often stale.', 'type': ['adjective'], 'synonym': 'still'},
    {'text': 'stern', 'diff': 2, 'def': 'Serious and strict.', 'type': ['adjective'], 'synonym': 'strict'},
    {'text': 'stoic', 'diff': 4, 'def': 'Able to suffer pain or hardship without showing feelings.', 'type': ['adjective', 'noun'], 'synonym': 'unemotional'},
    {'text': 'strive', 'diff': 3, 'def': 'To make a great effort to achieve something.', 'type': ['verb'], 'synonym': 'try'},
    {'text': 'sturdy', 'diff': 2, 'def': 'Strong and not easily damaged.', 'type': ['adjective'], 'synonym': 'solid'},
    {'text': 'subdue', 'diff': 4, 'def': 'To bring under control by force.', 'type': ['verb'], 'synonym': 'conquer'},
    {'text': 'submissive', 'diff': 3, 'def': 'Always obeying others and not resisting.', 'type': ['adjective'], 'synonym': 'obedient'},
    {'text': 'subsequent', 'diff': 3, 'def': 'Happening after something else.', 'type': ['adjective'], 'synonym': 'later'},
    {'text': 'succinct', 'diff': 4, 'def': 'Expressed clearly in a few words.', 'type': ['adjective'], 'synonym': 'concise'},
    {'text': 'suffice', 'diff': 3, 'def': 'To be enough.', 'type': ['verb'], 'synonym': 'satisfy'},
    {'text': 'superficial', 'diff': 3, 'def': 'On the surface only; not deep.', 'type': ['adjective'], 'synonym': 'shallow'},
    {'text': 'superior', 'diff': 2, 'def': 'Better than something else.', 'type': ['adjective', 'noun'], 'synonym': 'better'},
    {'text': 'supplement', 'diff': 3, 'def': 'Something added to improve or complete.', 'type': ['noun', 'verb'], 'synonym': 'add'},
    {'text': 'suppress', 'diff': 3, 'def': 'To stop something from being seen or expressed.', 'type': ['verb'], 'synonym': 'control'},
    {'text': 'surpass', 'diff': 3, 'def': 'To be better or greater than something else.', 'type': ['verb'], 'synonym': 'exceed'},
    {'text': 'surrender', 'diff': 2, 'def': 'To give up, especially in a fight.', 'type': ['verb', 'noun'], 'synonym': 'give in'},
    {'text': 'susceptible', 'diff': 4, 'def': 'Easily influenced or harmed by something.', 'type': ['adjective'], 'synonym': 'vulnerable'},
    {'text': 'tangible', 'diff': 4, 'def': 'That can be touched or clearly seen.', 'type': ['adjective'], 'synonym': 'real'},
    {'text': 'tedious', 'diff': 3, 'def': 'Long, slow, and boring.', 'type': ['adjective'], 'synonym': 'boring'},
    {'text': 'temperate', 'diff': 4, 'def': 'Mild; not extreme.', 'type': ['adjective'], 'synonym': 'mild'},
    {'text': 'tenacious', 'diff': 4, 'def': 'Holding on firmly; very determined.', 'type': ['adjective'], 'synonym': 'determined'},
    {'text': 'terminate', 'diff': 3, 'def': 'To bring something to an end.', 'type': ['verb'], 'synonym': 'end'},
    {'text': 'terrify', 'diff': 2, 'def': 'To frighten someone very much.', 'type': ['verb'], 'synonym': 'scare'},
    {'text': 'thrifty', 'diff': 3, 'def': 'Careful about spending money.', 'type': ['adjective'], 'synonym': 'economical'},
    {'text': 'timid', 'diff': 2, 'def': 'Shy and easily frightened.', 'type': ['adjective'], 'synonym': 'shy'},
    {'text': 'tolerant', 'diff': 2, 'def': 'Willing to accept opinions or behaviour that are different.', 'type': ['adjective'], 'synonym': 'open-minded'},
    {'text': 'tranquil', 'diff': 3, 'def': 'Calm and quiet.', 'type': ['adjective'], 'synonym': 'peaceful'},
    {'text': 'transparent', 'diff': 2, 'def': 'Allowing light through; or easy to understand.', 'type': ['adjective'], 'synonym': 'clear'},
    {'text': 'treacherous', 'diff': 4, 'def': 'Dangerous and not trustworthy.', 'type': ['adjective'], 'synonym': 'dangerous'},
    {'text': 'trivial', 'diff': 3, 'def': 'Small and not important.', 'type': ['adjective'], 'synonym': 'unimportant'},
    {'text': 'tyrant', 'diff': 3, 'def': 'A cruel and unfair ruler.', 'type': ['noun'], 'synonym': 'dictator'},
    {'text': 'ultimate', 'diff': 2, 'def': 'Final or best possible.', 'type': ['adjective'], 'synonym': 'final'},
    {'text': 'unanimous', 'diff': 3, 'def': 'With everyone in complete agreement.', 'type': ['adjective'], 'synonym': 'agreed'},
    {'text': 'undermine', 'diff': 3, 'def': 'To weaken something slowly.', 'type': ['verb'], 'synonym': 'weaken'},
    {'text': 'unruly', 'diff': 3, 'def': 'Badly behaved and hard to control.', 'type': ['adjective'], 'synonym': 'disorderly'},
    {'text': 'urgent', 'diff': 1, 'def': 'Needing immediate action.', 'type': ['adjective'], 'synonym': 'pressing'},
    {'text': 'utmost', 'diff': 2, 'def': 'Greatest or most extreme.', 'type': ['adjective', 'noun'], 'synonym': 'greatest'},
    {'text': 'vacant', 'diff': 2, 'def': 'Empty and not used.', 'type': ['adjective'], 'synonym': 'empty'},
    {'text': 'vague', 'diff': 2, 'def': 'Not clear or detailed.', 'type': ['adjective'], 'synonym': 'unclear'},
    {'text': 'valiant', 'diff': 3, 'def': 'Brave and determined.', 'type': ['adjective'], 'synonym': 'brave'},
    {'text': 'valid', 'diff': 2, 'def': 'Reasonable and correct; legally acceptable.', 'type': ['adjective'], 'synonym': 'sound'},
    {'text': 'vanquish', 'diff': 4, 'def': 'To defeat completely in battle or competition.', 'type': ['verb'], 'synonym': 'conquer'},
    {'text': 'venerate', 'diff': 4, 'def': 'To respect deeply.', 'type': ['verb'], 'synonym': 'revere'},
    {'text': 'verdict', 'diff': 3, 'def': 'The decision made by a jury in court.', 'type': ['noun'], 'synonym': 'judgement'},
    {'text': 'versatile', 'diff': 3, 'def': 'Able to do many different things well.', 'type': ['adjective'], 'synonym': 'multi-skilled'},
    {'text': 'vex', 'diff': 4, 'def': 'To annoy or worry someone.', 'type': ['verb'], 'synonym': 'irritate'},
    {'text': 'vibrant', 'diff': 2, 'def': 'Full of energy, colour, and life.', 'type': ['adjective'], 'synonym': 'lively'},
    {'text': 'vigorous', 'diff': 3, 'def': 'Strong, healthy, and full of energy.', 'type': ['adjective'], 'synonym': 'energetic'},
    {'text': 'vindictive', 'diff': 4, 'def': 'Wanting to hurt someone who has hurt you.', 'type': ['adjective'], 'synonym': 'vengeful'},
    {'text': 'vital', 'diff': 2, 'def': 'Extremely important and necessary.', 'type': ['adjective'], 'synonym': 'essential'},
    {'text': 'void', 'diff': 3, 'def': 'Completely empty; or having no legal effect.', 'type': ['adjective', 'noun'], 'synonym': 'empty'},
    {'text': 'volatile', 'diff': 4, 'def': 'Likely to change suddenly or become dangerous.', 'type': ['adjective'], 'synonym': 'unstable'},
    {'text': 'vulnerable', 'diff': 3, 'def': 'Easily hurt or harmed.', 'type': ['adjective'], 'synonym': 'exposed'},
    {'text': 'wane', 'diff': 4, 'def': 'To become weaker or smaller.', 'type': ['verb'], 'synonym': 'decline'},
    {'text': 'wary', 'diff': 3, 'def': 'Careful because something might be dangerous.', 'type': ['adjective'], 'synonym': 'cautious'},
    {'text': 'weary', 'diff': 2, 'def': 'Very tired and needing rest.', 'type': ['adjective'], 'synonym': 'tired'},
    {'text': 'whim', 'diff': 3, 'def': 'A sudden change of mind or desire.', 'type': ['noun'], 'synonym': 'impulse'},
    {'text': 'widespread', 'diff': 2, 'def': 'Happening in many places or among many people.', 'type': ['adjective'], 'synonym': 'common'},
    {'text': 'wither', 'diff': 3, 'def': 'To dry up and die; to weaken.', 'type': ['verb'], 'synonym': 'shrivel'},
    {'text': 'witless', 'diff': 3, 'def': 'Stupid or silly.', 'type': ['adjective'], 'synonym': 'foolish'},
    {'text': 'wretched', 'diff': 3, 'def': 'Very unhappy or in a very bad state.', 'type': ['adjective'], 'synonym': 'miserable'},
    {'text': 'yearn', 'diff': 3, 'def': 'To want something very much.', 'type': ['verb'], 'synonym': 'long'},
    {'text': 'zealous', 'diff': 4, 'def': 'Showing great energy and enthusiasm for a cause.', 'type': ['adjective'], 'synonym': 'enthusiastic'},
    {'text': 'zenith', 'diff': 4, 'def': 'The highest point of success or power.', 'type': ['noun'], 'synonym': 'peak'},
]
