# A mix of moderate to difficult 11+ words
WORD_LIST = [
    {"text": "absurd", "diff": 3, "def": "Wildly unreasonable, illogical, or inappropriate."},
    {"text": "abundant", "diff": 4, "def": "Existing or available in large quantities; plentiful."},
    {"text": "accommodate", "diff": 6, "def": "Fit in with the wishes or needs of."},
    {"text": "accumulate", "diff": 5, "def": "Gather together or acquire an increasing number of."},
    {"text": "acquire", "diff": 4, "def": "Buy or obtain for oneself."},
    {"text": "ambitious", "diff": 5, "def": "Having or showing a strong desire and determination to succeed."},
    {"text": "ancient", "diff": 2, "def": "Belonging to the very distant past and no longer in existence."},
    {"text": "anxious", "diff": 3, "def": "Experiencing worry, unease, or nervousness."},
    {"text": "apparent", "diff": 4, "def": "Clearly visible or understood; obvious."},
    {"text": "arduous", "diff": 7, "def": "Involving or requiring strenuous effort; difficult and tiring."},
    {"text": "assemble", "diff": 3, "def": "Gather together in one place for a common purpose."},
    {"text": "belligerent", "diff": 8, "def": "Hostile and aggressive."},
    {"text": "bewildered", "diff": 6, "def": "Perplexed and confused; very puzzled."},
    {"text": "calamity", "diff": 7, "def": "An event causing great and often sudden damage or distress."},
    {"text": "candidate", "diff": 4, "def": "A person who applies for a job or is nominated for election."},
    {"text": "capacity", "diff": 4, "def": "The maximum amount that something can contain."},
    {"text": "cease", "diff": 3, "def": "Bring or come to an end."},
    {"text": "chaos", "diff": 5, "def": "Complete disorder and confusion."},
    {"text": "chronological", "diff": 8, "def": "Starting with the earliest and following the order in which they occurred."},
    {"text": "coarse", "diff": 4, "def": "Rough or loose in texture or grain."},
    {"text": "collaborate", "diff": 6, "def": "Work jointly on an activity, especially to produce or create something."},
    {"text": "commence", "diff": 5, "def": "Begin; start."},
    {"text": "competent", "diff": 5, "def": "Having the necessary ability, knowledge, or skill to do something successfully."},
    {"text": "conceal", "diff": 4, "def": "Keep from sight; hide."},
    {"text": "conscience", "diff": 7, "def": "An inner feeling or voice viewed as acting as a guide to the rightness or wrongness of one's behavior."},
    {"text": "continuous", "diff": 5, "def": "Forming an unbroken whole; without interruption."},
    {"text": "controversy", "diff": 7, "def": "Disagreement, typically when prolonged, public, and heated."},
    {"text": "convenient", "diff": 5, "def": "Fitting in well with a person's needs, activities, and plans."},
    {"text": "courageous", "diff": 5, "def": "Not deterred by danger or pain; brave."},
    {"text": "curiosity", "diff": 4, "def": "A strong desire to know or learn something."},
    {"text": "deceive", "diff": 4, "def": "Cause (someone) to believe something that is not true."},
    {"text": "deficiency", "diff": 7, "def": "A lack or shortage."},
    {"text": "deliberate", "diff": 5, "def": "Done consciously and intentionally."},
    {"text": "desperate", "diff": 4, "def": "Feeling, showing, or involving a hopeless sense that a situation is so bad as to be impossible to deal with."},
    {"text": "deteriorate", "diff": 8, "def": "Become progressively worse."},
    {"text": "dilemma", "diff": 6, "def": "A situation in which a difficult choice has to be made between two or more alternatives."},
    {"text": "diligent", "diff": 6, "def": "Having or showing care and conscientiousness in one's work or duties."},
    {"text": "disaster", "diff": 3, "def": "A sudden event, such as an accident or a natural catastrophe, that causes great damage or loss of life."},
    {"text": "distinct", "diff": 4, "def": "Recognizably different in nature from something else of a similar type."},
    {"text": "elaborate", "diff": 5, "def": "Involving many carefully arranged parts or details; detailed and complicated in design and planning."},
    {"text": "encourage", "diff": 4, "def": "Give support, confidence, or hope to (someone)."},
    {"text": "environment", "diff": 5, "def": "The surroundings or conditions in which a person, animal, or plant lives or operates."},
    {"text": "essential", "diff": 3, "def": "Absolutely necessary; extremely important."},
    {"text": "exaggerate", "diff": 6, "def": "Represent (something) as being larger, better, or worse than it really is."},
    {"text": "exhausted", "diff": 4, "def": "Drained of one's physical or mental resources; very tired."},
    {"text": "existence", "diff": 4, "def": "The fact or state of living or having objective reality."},
    {"text": "extravagant", "diff": 7, "def": "Lacking restraint in spending money or using resources."},
    {"text": "familiar", "diff": 3, "def": "Well known from long or close association."},
    {"text": "fatal", "diff": 2, "def": "Causing death."},
    {"text": "ferocious", "diff": 5, "def": "Savagely fierce, cruel, or violent."},
    {"text": "flamboyant", "diff": 8, "def": "(of a person or their behavior) tending to attract attention because of their exuberance, confidence, and stylishness."},
    {"text": "frequent", "diff": 3, "def": "Occurring or done on many occasions, in many cases, or in quick succession."},
    {"text": "generous", "diff": 3, "def": "Showing a readiness to give more of something, as money or time, than is strictly necessary or expected."},
    {"text": "genuine", "diff": 4, "def": "Truly what something is said to be; authentic."},
    {"text": "grief", "diff": 3, "def": "Deep sorrow, especially that caused by someone's death."},
    {"text": "guarantee", "diff": 5, "def": "A formal promise or assurance (typically in writing) that certain conditions will be fulfilled."},
    {"text": "harass", "diff": 4, "def": "Subject to aggressive pressure or intimidation."},
    {"text": "hesitate", "diff": 4, "def": "Pause before saying or doing something, often through uncertainty."},
    {"text": "hostile", "diff": 4, "def": "Unfriendly; antagonistic."},
    {"text": "humorous", "diff": 4, "def": "Causing lighthearted laughter and amusement; comic."},
    {"text": "identical", "diff": 4, "def": "Similar in every detail; exactly alike."},
    {"text": "ignorant", "diff": 4, "def": "Lacking knowledge or awareness in general; uneducated or unsophisticated."},
    {"text": "imitate", "diff": 3, "def": "Take or follow as a model."},
    {"text": "immediate", "diff": 4, "def": "Occurring or done at once; instant."},
    {"text": "immense", "diff": 4, "def": "Extremely large or great, especially in scale or degree."},
    {"text": "impatient", "diff": 4, "def": "Having or showing a tendency to be quickly irritated or provoked."},
    {"text": "implement", "diff": 5, "def": "Put (a decision, plan, agreement, etc.) into effect."},
]
